<?php
$method = $_SERVER['REQUEST_METHOD'];  
$response = [];
$statusCode = 200;
$ok = true; 
$ok = $ok && ($method === 'POST');
$ok || ($statusCode = 405 && $response = ['error' => 'Метод не разрешён. Используйте POST.']);
$ok = $ok && ($json = file_get_contents('php://input'));
$ok || ($statusCode = 400 && $response = ['error' => 'Пустой запрос']);
$ok = $ok && is_array($data = json_decode($json, true));
$ok || ($statusCode = 400 && $response = ['error' => 'Некорректный JSON']);
$ok = $ok && !empty($data['image']);
$ok || ($statusCode = 400 && $response = ['error' => 'Поле image отсутствует']);
$rawImage = $data['image'];
$hasPrefix = (strpos($rawImage, 'base64,') !== false);
$parts = explode('base64,', $rawImage);
$imageData = $rawImage;
$hasPrefix && ($imageData = $parts[1]);
$binary = base64_decode($imageData, true);
$ok = $ok && ($binary !== false);
$ok || ($statusCode = 400 && $response = ['error' => 'Некорректный base64']);
$ok && (!is_dir('static')) && mkdir('static', 0777, true);
$filename = 'img_' . time() . '.png';
$filepath = 'static/' . $filename;
$ok = $ok && (file_put_contents($filepath, $binary) !== false);
$ok || ($statusCode = 500 && $response = ['error' => 'Ошибка сохранения файла']);
$ok && ($response = ['success' => true, 'file' => $filepath]);

http_response_code($statusCode);
header('Content-Type: application/json; charset=UTF-8');
echo json_encode($response, JSON_UNESCAPED_UNICODE);